// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvdqxmnxtzaramcuggtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2ZHF4bW54dHphcmFtY3VnZ3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTY2NDcsImV4cCI6MjA2OTkzMjY0N30.0Xp0a7bnnlXPnAw9AhjGvJjuaAoGuo5vuz9_cKSVYS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});